apiVersion: v1
kind: Service
metadata:
  name: followupfinder-ai
  namespace: followupfinder

spec:
  selector:
    app: followupfinder-ai

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: ClusterIP