replicaCount: 1

image:
  repository: docker.io/aditya1961/followupfinder-ai
  tag: "1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ai:
  device: cpu
  baseModelPath: /models/Qwen3-0.6B
  adapterPath: /models/lora-round3

models:
  baseModelHostPath: /models/Qwen3-0.6B
  adapterHostPath: /models/lora-round3
