replicaCount: 2

image:
  repository: aditya1961/followupfinder-ai
  tag: "5"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ai:
  device: cpu
  baseModelPath: /models/Qwen3-0.6B
  adapterPath: /models/lora-round4

models:
  baseModelHostPath: /models/Qwen3-0.6B
  adapterHostPath: /models/lora-round4
