apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}

data:
  FOLLOWUPFINDER_DEVICE: {{ .Values.ai.device | quote }}
  FOLLOWUPFINDER_BASE_MODEL_PATH: {{ .Values.ai.baseModelPath | quote }}
  FOLLOWUPFINDER_ADAPTER_PATH: {{ .Values.ai.adapterPath | quote }}
